name: Nigiri pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Nigiri
        uses: vulpemventures/nigiri-github-action@v1
        with:
          use_liquid: false
      - name: Install dependencies
        run: |
          pip install -r requirements.txt && pip install -r test_requirements.txt
          pip install -e .
      - name: Run integration tests
        run: |
          pytest tests/wallet_import_rescan.py
        