name: Run Python tests

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r test_requirements.txt
          pip3 install -e .
          pip3 install pytest pytest-md pytest-emoji
      - name: pytest
        run: |
          pytest